### ISSUE TITLE
Object Preview Bugged

### ISSUE THREAD

**Issue by Julius-A4** [wafflesgama/LazyBuilderLibrary#1]
Hello there! 

Ran into some bugs with the object preview window while testing out the package. The background of the window is all red and when I pan the view of the object to a more straight on front profile the whole preview screen goes pink. Im on Unity ver 2022.1.16f1.

![image](https://user-images.githubusercontent.com/45527828/202359410-352fe21d-4fdc-426a-a34c-11c9eb969400.png)

https://user-images.githubusercontent.com/45527828/202361018-5ce2e26d-3858-4885-a546-0e1d0e713eec.mp4

**Comment by wafflesgama** [comment]
Hi! This seems to be an issue related to the tool itself and not related to the library assets structure. Could you please repost this in the [Tool's Repository](https://github.com/wafflesgama/LazyBuilder)?

For further readers: Please post here solely issues related to the assets (ie. back-face culling, missing materials, weird topology) and file/folder structure (ie. missing thumbnails, missing files, wrong item naming)
